"""
MDDE Lite - Simple SQL Optimizer

SQL quality checks that detect common anti-patterns.

Checks included (20 total):

Anti-Pattern Checks (15):
- SELECT_STAR: SELECT * usage
- MISSING_ALIAS: Tables without aliases in JOINs
- ORDER_BY_NUMBER: ORDER BY column number instead of name
- IMPLICIT_JOIN: Comma-separated FROM (implicit join)
- WHERE_1_EQUALS_1: WHERE 1=1 pattern
- DISTINCT_STAR: SELECT DISTINCT * pattern
- CARTESIAN_JOIN: JOIN without ON clause
- DUPLICATE_COLUMN: Same column selected twice
- NESTED_SUBQUERY: Deep subquery nesting (3+ levels)
- UNION_COLUMN_MISMATCH: Mismatched column counts in UNION
- LEADING_WILDCARD: LIKE '%...' pattern (non-SARGable)
- FUNCTION_IN_WHERE: Function on column in WHERE (non-SARGable)
- OR_IN_JOIN: OR condition in JOIN ON clause
- HARDCODED_DATE: Hardcoded date literals
- MISSING_GROUP_BY: Aggregate function without GROUP BY

Determinism Checks (5):
- WINDOW_NO_ORDER: ROW_NUMBER/RANK without ORDER BY
- WINDOW_NON_UNIQUE_ORDER: ORDER BY may not be unique
- LIMIT_NO_ORDER: LIMIT/TOP without ORDER BY
- VOLATILE_FUNCTION: RANDOM(), NOW(), UUID() usage
- FIRST_LAST_NO_ORDER: FIRST_VALUE/LAST_VALUE without ORDER BY

Related articles:
- "Implementing 25 Essential Data Quality Checks Using YAML Metadata"
- "Testing Query Migrations Using Synthetic Data"
- "Deterministic SQL Generation Is a Hard Invariant"

This is a simplified version. The full MDDE optimizer includes:
- CTE normalization and optimization
- UNION handling and column alignment
- Advanced dialect rendering
- Performance recommendations
- Filter/join pushdown analysis
- Automatic tie-breaker suggestions
- DQ monitoring column generation
"""

"""
NOTE — vendored from src/mdde_lite/optimizer.py for portability.
DuckDB persistence (analyze_file / analyze_directory) has been removed
so this module runs in any environment with sqlglot installed
(including a Databricks notebook with no DuckDB available).

Do not edit this file directly — it is a vendor copy. Re-vendor by
copying the upstream module and removing the duckdb / .schema imports
plus the analyze_file/analyze_directory functions.
"""

import sqlglot
from sqlglot import exp
from typing import List
import uuid


def generate_id() -> str:
    """Generate a short unique ID."""
    return str(uuid.uuid4())[:8]


class SQLDiagnostic:
    """Represents a SQL quality finding."""

    def __init__(
        self,
        diagnostic_type: str,
        message: str,
        severity: str = "warning",
        line_number: int = None,
        suggestion: str = None,
    ):
        self.diagnostic_type = diagnostic_type
        self.message = message
        self.severity = severity
        self.line_number = line_number
        self.suggestion = suggestion

    def __repr__(self):
        return f"[{self.severity.upper()}] {self.diagnostic_type}: {self.message}"


def check_select_star(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect SELECT * usage."""
    diagnostics = []

    for star in parsed.find_all(exp.Star):
        diagnostics.append(SQLDiagnostic(
            diagnostic_type="SELECT_STAR",
            message="SELECT * detected - explicit column list recommended",
            severity="warning",
            suggestion="Replace * with explicit column names for better maintainability and performance",
        ))

    return diagnostics


def check_missing_alias(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect tables without aliases in JOINs."""
    diagnostics = []

    # Find all tables
    tables = list(parsed.find_all(exp.Table))

    if len(tables) > 1:
        for table in tables:
            if not table.alias:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="MISSING_ALIAS",
                    message=f"Table '{table.name}' has no alias in multi-table query",
                    severity="info",
                    suggestion=f"Add alias: {table.name} AS {table.name[0].lower()}",
                ))

    return diagnostics


def check_order_by_number(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect ORDER BY column number instead of name."""
    diagnostics = []

    for order in parsed.find_all(exp.Order):
        for expr in order.expressions:
            if isinstance(expr.this, exp.Literal) and expr.this.is_int:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="ORDER_BY_NUMBER",
                    message=f"ORDER BY uses column number ({expr.this.this}) instead of name",
                    severity="warning",
                    suggestion="Use column name for clarity and maintainability",
                ))

    return diagnostics


def check_implicit_join(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect implicit joins (comma-separated FROM)."""
    diagnostics = []

    # This is a simplified check - look for multiple tables in FROM without JOIN
    select = parsed.find(exp.Select)
    if select:
        from_clause = select.find(exp.From)
        if from_clause:
            # If there are multiple tables but no JOIN keywords, it might be implicit
            tables = list(select.find_all(exp.Table))
            joins = list(select.find_all(exp.Join))

            if len(tables) > 1 and len(joins) < len(tables) - 1:
                # Check if it's actually comma-separated
                from_sql = from_clause.sql()
                if "," in from_sql:
                    diagnostics.append(SQLDiagnostic(
                        diagnostic_type="IMPLICIT_JOIN",
                        message="Implicit join (comma-separated FROM) detected",
                        severity="warning",
                        suggestion="Use explicit JOIN syntax for clarity",
                    ))

    return diagnostics


def check_where_one_equals_one(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect WHERE 1=1 pattern."""
    diagnostics = []

    where = parsed.find(exp.Where)
    if where:
        where_sql = where.sql().upper()
        if "1=1" in where_sql or "1 = 1" in where_sql:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="WHERE_1_EQUALS_1",
                message="WHERE 1=1 pattern detected",
                severity="info",
                suggestion="Remove if not needed for dynamic SQL generation",
            ))

    return diagnostics


# ============================================================
# NEW CHECKS (expanding from 5 to 15)
# ============================================================


def check_distinct_star(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect SELECT DISTINCT * pattern."""
    diagnostics = []

    for select in parsed.find_all(exp.Select):
        if select.args.get("distinct"):
            for expr in select.expressions:
                if isinstance(expr, exp.Star):
                    diagnostics.append(SQLDiagnostic(
                        diagnostic_type="DISTINCT_STAR",
                        message="SELECT DISTINCT * detected",
                        severity="warning",
                        suggestion="Use explicit column list with DISTINCT for clarity and performance",
                    ))
                    break

    return diagnostics


def check_cartesian_join(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect JOIN without ON clause (potential cartesian product)."""
    diagnostics = []

    for join in parsed.find_all(exp.Join):
        # Check if join has ON condition
        if not join.args.get("on") and not join.args.get("using"):
            # CROSS JOIN is intentional, others are suspicious
            join_type = join.args.get("kind", "").upper() if join.args.get("kind") else ""
            if "CROSS" not in join_type:
                table_name = join.this.name if hasattr(join.this, 'name') else str(join.this)
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="CARTESIAN_JOIN",
                    message=f"JOIN to '{table_name}' without ON clause - potential cartesian product",
                    severity="warning",
                    suggestion="Add ON clause or use CROSS JOIN if intentional",
                ))

    return diagnostics


def check_duplicate_column(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect same column selected twice in SELECT clause."""
    diagnostics = []

    for select in parsed.find_all(exp.Select):
        seen_columns = {}
        for expr in select.expressions:
            col_name = None
            if isinstance(expr, exp.Column):
                col_name = expr.name.lower()
            elif isinstance(expr, exp.Alias):
                col_name = expr.alias.lower()

            if col_name:
                if col_name in seen_columns:
                    diagnostics.append(SQLDiagnostic(
                        diagnostic_type="DUPLICATE_COLUMN",
                        message=f"Column '{col_name}' appears multiple times in SELECT",
                        severity="warning",
                        suggestion="Remove duplicate or use different alias",
                    ))
                else:
                    seen_columns[col_name] = True

    return diagnostics


def check_nested_subquery(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect deeply nested subqueries (3+ levels)."""
    diagnostics = []

    def count_depth(node, current_depth=0):
        max_depth = current_depth
        for child in node.iter_expressions():
            if isinstance(child, exp.Subquery):
                child_depth = count_depth(child, current_depth + 1)
                max_depth = max(max_depth, child_depth)
            else:
                child_depth = count_depth(child, current_depth)
                max_depth = max(max_depth, child_depth)
        return max_depth

    depth = count_depth(parsed)
    if depth >= 3:
        diagnostics.append(SQLDiagnostic(
            diagnostic_type="NESTED_SUBQUERY",
            message=f"Deeply nested subqueries detected ({depth} levels)",
            severity="info",
            suggestion="Consider using CTEs for better readability",
        ))

    return diagnostics


def check_union_column_mismatch(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect UNION/UNION ALL with different column counts."""
    diagnostics = []

    for union in parsed.find_all(exp.Union):
        left = union.this
        right = union.expression

        # Count columns in each side
        left_cols = len(list(left.find(exp.Select).expressions)) if left.find(exp.Select) else 0
        right_cols = len(list(right.find(exp.Select).expressions)) if right.find(exp.Select) else 0

        if left_cols != right_cols and left_cols > 0 and right_cols > 0:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="UNION_COLUMN_MISMATCH",
                message=f"UNION has mismatched column counts: {left_cols} vs {right_cols}",
                severity="error",
                suggestion="Ensure both sides of UNION have same number of columns",
            ))

    return diagnostics


def check_leading_wildcard(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect LIKE '%...' pattern (non-SARGable)."""
    diagnostics = []

    for like in parsed.find_all(exp.Like):
        pattern = like.expression
        if isinstance(pattern, exp.Literal) and pattern.is_string:
            pattern_value = pattern.this
            if pattern_value.startswith('%'):
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="LEADING_WILDCARD",
                    message=f"LIKE pattern starts with '%' - cannot use index",
                    severity="info",
                    suggestion="Consider full-text search or restructure query if performance critical",
                ))

    return diagnostics


def check_function_in_where(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect function applied to column in WHERE clause (non-SARGable)."""
    diagnostics = []

    where = parsed.find(exp.Where)
    if where:
        # Look for common patterns: UPPER(col), LOWER(col), YEAR(col), etc.
        for func in where.find_all(exp.Func):
            # Check if function is applied to a column (not a literal)
            for arg in func.expressions:
                if isinstance(arg, exp.Column):
                    func_name = func.key.upper() if hasattr(func, 'key') else type(func).__name__.upper()
                    diagnostics.append(SQLDiagnostic(
                        diagnostic_type="FUNCTION_IN_WHERE",
                        message=f"Function {func_name} on column in WHERE - cannot use index",
                        severity="info",
                        suggestion="Consider computed column or functional index",
                    ))
                    break

    return diagnostics


def check_or_in_join(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect OR condition in JOIN ON clause."""
    diagnostics = []

    for join in parsed.find_all(exp.Join):
        on_clause = join.args.get("on")
        if on_clause:
            # Check for OR at the top level of the ON clause
            if isinstance(on_clause, exp.Or):
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="OR_IN_JOIN",
                    message="OR condition in JOIN ON clause",
                    severity="warning",
                    suggestion="Consider UNION of separate JOINs for better optimization",
                ))
            # Also check for OR nested in AND
            for or_expr in on_clause.find_all(exp.Or):
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="OR_IN_JOIN",
                    message="OR condition in JOIN ON clause",
                    severity="warning",
                    suggestion="Consider UNION of separate JOINs for better optimization",
                ))
                break  # Only report once per join

    return diagnostics


def check_hardcoded_date(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect hardcoded date literals."""
    diagnostics = []

    # Common date patterns
    import re
    date_pattern = re.compile(r"^\d{4}-\d{2}-\d{2}$|^\d{2}/\d{2}/\d{4}$|^\d{8}$")

    for literal in parsed.find_all(exp.Literal):
        if literal.is_string:
            value = str(literal.this)
            if date_pattern.match(value):
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="HARDCODED_DATE",
                    message=f"Hardcoded date literal: '{value}'",
                    severity="info",
                    suggestion="Consider using parameters or date functions",
                ))

    return diagnostics


def check_missing_group_by(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Detect aggregate function without GROUP BY."""
    diagnostics = []

    aggregate_funcs = (exp.Count, exp.Sum, exp.Avg, exp.Min, exp.Max)

    for select in parsed.find_all(exp.Select):
        has_aggregate = False
        has_non_aggregate = False

        for expr in select.expressions:
            # Check if this expression contains an aggregate
            if any(expr.find(agg) for agg in aggregate_funcs):
                has_aggregate = True
            elif isinstance(expr, exp.Column):
                has_non_aggregate = True
            elif isinstance(expr, exp.Alias):
                inner = expr.this
                if any(inner.find(agg) for agg in aggregate_funcs):
                    has_aggregate = True
                elif isinstance(inner, exp.Column):
                    has_non_aggregate = True

        # If we have both aggregates and non-aggregates, need GROUP BY
        if has_aggregate and has_non_aggregate:
            group = select.args.get("group")
            if not group:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="MISSING_GROUP_BY",
                    message="Aggregate function mixed with non-aggregated columns without GROUP BY",
                    severity="error",
                    suggestion="Add GROUP BY clause or wrap non-aggregates in aggregate functions",
                ))

    return diagnostics


# ============================================================
# CUSTOMER RULE-PACK CHECKS
# ============================================================
#
# These detection rules implement the customer's consolidated SQL
# migration rule set (see CUSTOMER_RULES.md). Each function follows
# the convention: input a parsed AST + an optional config dict,
# return a list of SQLDiagnostic.
#
# Config dict shape (all keys optional):
#   {
#     "legacy_schemas": ["bodm", "csz", "hz", "cz"],
#     "replacement_schema": "automatically_inferred_qualifier",
#     "date_variable": "process_date",
#     "metadata_blacklist": [
#       "snapshot_date", "insert_dts", "update_dts", "current_flag",
#       "delete_flag", "delta_flag", "create_timestamp",
#       "start_dts", "end_dts",
#     ],
#     "obsolete_cte_names": [
#       "extract_dates", "create_timeline", "finalize_timeline",
#     ],
#   }


_DEFAULT_METADATA_BLACKLIST = (
    "snapshot_date",
    "insert_dts",
    "update_dts",
    "current_flag",
    "delete_flag",
    "delta_flag",
    "create_timestamp",
    "start_dts",
    "end_dts",
)

_DEFAULT_OBSOLETE_CTES = (
    "extract_dates",
    "create_timeline",
    "finalize_timeline",
)


def check_legacy_schema(parsed: exp.Expression, config: dict) -> List[SQLDiagnostic]:
    """Rule 1: legacy schema references (`bodm`, `csz`, `hz`, `cz`)
    should be replaced with `automatically_inferred_qualifier`."""
    diagnostics = []
    legacy = set(config.get("legacy_schemas") or [])
    if not legacy:
        return diagnostics
    replacement = config.get("replacement_schema", "automatically_inferred_qualifier")
    for tbl in parsed.find_all(exp.Table):
        db = tbl.args.get("db")
        if db is not None and db.name in legacy:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="LEGACY_SCHEMA",
                message=f"Legacy schema '{db.name}' should be replaced with '{replacement}'",
                severity="warning",
                suggestion=f"Replace '{db.name}.{tbl.name}' with '{replacement}.{tbl.name}'",
            ))
    return diagnostics


def check_legacy_date_variable(sql_content: str, config: dict) -> List[SQLDiagnostic]:
    """Rule 2: replace legacy `{reporting_date}` with `{process_date}`.

    Operates on raw SQL because template variables aren't part of the
    parsed AST (sqlglot treats `{reporting_date}` as an identifier or
    error depending on context)."""
    diagnostics = []
    target = config.get("date_variable", "process_date")
    legacy_variants = ("reporting_date",)
    for legacy in legacy_variants:
        if legacy == target:
            continue
        if "{" + legacy + "}" in sql_content:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="LEGACY_DATE_VARIABLE",
                message=f"Legacy template variable '{{{legacy}}}' should be '{{{target}}}'",
                severity="warning",
                suggestion=f"Replace '{{{legacy}}}' with '{{{target}}}'",
            ))
    return diagnostics


def check_between_for_scd2(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule 2: `BETWEEN` must not be used for SCD2-style filtering.

    Flags `WHERE x BETWEEN _valid_from AND _valid_to` patterns and the
    legacy `snapshot_date BETWEEN start_dts AND end_dts` pattern."""
    diagnostics = []
    scd2_cols = {"_valid_from", "_valid_to", "start_dts", "end_dts"}
    for between in parsed.find_all(exp.Between):
        cols = [c.name for c in between.find_all(exp.Column)]
        if any(c in scd2_cols for c in cols):
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="BETWEEN_FOR_SCD2",
                message="BETWEEN used for SCD2/snapshot-date filtering",
                severity="warning",
                suggestion=(
                    "Use explicit >= _valid_from AND < COALESCE(_valid_to, ...) "
                    "predicates instead of BETWEEN"
                ),
            ))
    return diagnostics


def check_obsolete_cte(parsed: exp.Expression, config: dict) -> List[SQLDiagnostic]:
    """Rule 3: identify CTEs whose names match the obsolete-timeline
    blacklist (`extract_dates`, `create_timeline`, `finalize_timeline`)."""
    diagnostics = []
    blacklist = set(config.get("obsolete_cte_names") or _DEFAULT_OBSOLETE_CTES)
    for cte in parsed.find_all(exp.CTE):
        name = cte.alias_or_name
        if name in blacklist:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="OBSOLETE_CTE",
                message=f"CTE '{name}' is obsolete under SCD2 filtering",
                severity="warning",
                suggestion="Remove this CTE; downstream queries should read directly from the SCD2-filtered source",
            ))
    return diagnostics


def check_metadata_column_exposed(parsed: exp.Expression, config: dict) -> List[SQLDiagnostic]:
    """Rule 4: metadata columns must not appear in CTE/final outputs.

    Walks every Select's projections; flags any column whose name
    matches the metadata blacklist (case-insensitive) when it appears
    as an output column (not inside a WHERE predicate)."""
    diagnostics = []
    blacklist = {
        b.lower() for b in (config.get("metadata_blacklist") or _DEFAULT_METADATA_BLACKLIST)
    }
    for select in parsed.find_all(exp.Select):
        for proj in select.expressions:
            col_name = None
            if isinstance(proj, exp.Column):
                col_name = proj.name
            elif isinstance(proj, exp.Alias):
                col_name = proj.alias
                # Also catch `metadata_col AS something` — the source
                # is what's blacklisted.
                inner = proj.this
                if isinstance(inner, exp.Column) and inner.name.lower() in blacklist:
                    diagnostics.append(SQLDiagnostic(
                        diagnostic_type="METADATA_COLUMN_EXPOSED",
                        message=f"Metadata column '{inner.name}' exposed in output (as '{col_name}')",
                        severity="warning",
                        suggestion=f"Remove '{inner.name}' from output; it should not propagate downstream",
                    ))
                    continue
            if col_name and col_name.lower() in blacklist:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="METADATA_COLUMN_EXPOSED",
                    message=f"Metadata column '{col_name}' exposed in output",
                    severity="warning",
                    suggestion=f"Remove '{col_name}' from output; it should not propagate downstream",
                ))
    return diagnostics


def check_unused_left_join(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule 5: LEFT JOINs that contribute no columns to the SELECT
    (and aren't used in downstream joins/filters) should be removed."""
    diagnostics = []
    select = parsed.find(exp.Select)
    if select is None:
        return diagnostics

    for join in select.args.get("joins") or []:
        side = (join.args.get("side") or "").upper()
        if side != "LEFT":
            continue
        # Find the join's table alias.
        join_target = join.this
        if not isinstance(join_target, exp.Table):
            continue
        alias = join_target.alias or join_target.name
        if not alias:
            continue
        # Check whether any Column anywhere in the outer Select (other
        # than this Join's ON clause) qualifies with this alias.
        contributes = False
        for col in select.find_all(exp.Column):
            if col.table == alias:
                # Exclude refs that live inside the Join's own ON clause.
                ancestor = col.parent
                inside_this_join = False
                while ancestor is not None:
                    if ancestor is join:
                        inside_this_join = True
                        break
                    ancestor = ancestor.parent
                if not inside_this_join:
                    contributes = True
                    break
        if not contributes:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="UNUSED_LEFT_JOIN",
                message=f"LEFT JOIN to '{alias}' contributes no columns and may be removable",
                severity="info",
                suggestion="Verify the join is needed for filtering side-effects; if not, remove it",
            ))
    return diagnostics


def check_inline_cast_in_join(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Pre-Processed Joins rule: no inline CAST / function / literal
    in JOIN ON conditions. Materialise transformed keys in CTEs."""
    diagnostics = []
    for join in parsed.find_all(exp.Join):
        on = join.args.get("on")
        if on is None:
            continue
        for cast in on.find_all(exp.Cast):
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="INLINE_CAST_IN_JOIN",
                message=f"Inline CAST in JOIN ON clause: {cast.sql()}",
                severity="warning",
                suggestion="Pre-compute the transformed column in a CTE, then join on the prepared column",
            ))
        # Inline literals in the ON-clause (other than NULL / TRUE / FALSE).
        for lit in on.find_all(exp.Literal):
            if lit.is_string or lit.is_int:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="LITERAL_IN_JOIN",
                    message=f"Literal in JOIN ON clause: {lit.sql()}",
                    severity="info",
                    suggestion="Move the literal into a CTE filter; join on prepared columns only",
                ))
                break  # one finding per join is enough
    return diagnostics


def check_derivation_in_where(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: pre-compute Boolean fields; WHERE should reference them,
    not perform `IS NOT NULL` / `CAST` / function calls on raw columns."""
    diagnostics = []
    boolean_prefixes = ("is_", "has_")
    boolean_suffixes = ("_flag",)
    for where in parsed.find_all(exp.Where):
        # Function calls applied to columns inside WHERE.
        for func in where.find_all(exp.Func):
            if any(isinstance(a, exp.Column) for a in func.args.values() if a is not None):
                func_name = type(func).__name__.upper()
                if func_name in ("AND", "OR", "NOT", "PAREN"):
                    continue
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="DERIVATION_IN_WHERE",
                    message=f"Function call ({func_name}) on column inside WHERE",
                    severity="info",
                    suggestion="Pre-compute as a Boolean column (e.g., is_valid, has_value) in the source CTE and reference it in WHERE",
                ))
                break
        # `<col> IS NOT NULL` on a non-Boolean column.
        for is_null in where.find_all(exp.Is):
            col = is_null.this
            if not isinstance(col, exp.Column):
                continue
            name = (col.name or "").lower()
            if name.startswith(boolean_prefixes) or name.endswith(boolean_suffixes):
                continue
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="DERIVATION_IN_WHERE",
                message=f"IS [NOT] NULL on raw column '{name}' inside WHERE",
                severity="info",
                suggestion=f"Pre-compute 'has_{name}' (or similar Boolean) in the source CTE",
            ))
            break  # one finding per where is enough
    return diagnostics


def check_inline_union_transform(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: UNION ALL must be 'pure' — only concatenate already-prepared
    datasets. No casts, filters, or new expression columns inside the
    UNION branches."""
    diagnostics = []
    for union in parsed.find_all(exp.Union):
        for branch in (union.this, union.expression):
            if branch is None:
                continue
            branch_select = branch if isinstance(branch, exp.Select) else branch.find(exp.Select)
            if branch_select is None:
                continue
            # Any Cast / Func / non-bare-column projection?
            for proj in branch_select.expressions:
                if isinstance(proj, exp.Column) or isinstance(proj, exp.Star):
                    continue
                if isinstance(proj, exp.Alias):
                    inner = proj.this
                    if isinstance(inner, exp.Column) or isinstance(inner, exp.Literal):
                        continue
                # Anything else is a derivation inside the UNION branch.
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="INLINE_UNION_TRANSFORM",
                    message=f"Transformation inside UNION ALL branch: {proj.sql()[:80]}",
                    severity="warning",
                    suggestion="Move transformations into per-source CTEs; UNION ALL should only concatenate prepared data",
                ))
                break
            # Filter inside the branch?
            if branch_select.args.get("where"):
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="INLINE_UNION_TRANSFORM",
                    message="WHERE clause inside UNION ALL branch",
                    severity="warning",
                    suggestion="Move filtering into per-source CTEs before the UNION ALL",
                ))
    return diagnostics


def check_combined_source_filters(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: filters for multiple sources must not be combined into a
    single WHERE clause. Each source should be filtered in its own
    initial CTE."""
    diagnostics = []
    for where in parsed.find_all(exp.Where):
        # Collect the table aliases referenced inside this WHERE.
        aliases = set()
        for col in where.find_all(exp.Column):
            if col.table:
                aliases.add(col.table)
        # Cross-table predicate from at least 2 distinct sources?
        if len(aliases) >= 2:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="COMBINED_SOURCE_FILTERS",
                message=f"WHERE clause references columns from {len(aliases)} sources ({', '.join(sorted(aliases))})",
                severity="info",
                suggestion="Split into per-source filters in initial CTEs; the outer WHERE should be empty or cross-source-join-only",
            ))
    return diagnostics


def check_groupby_not_isolated(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: GROUP BY must be in its own dedicated CTE. A Select with
    GROUP BY *and* a WHERE *and* joins is mixing concerns."""
    diagnostics = []
    for select in parsed.find_all(exp.Select):
        if select.args.get("group") is None:
            continue
        has_where = select.args.get("where") is not None
        has_joins = bool(select.args.get("joins"))
        if has_where and has_joins:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="GROUPBY_NOT_ISOLATED",
                message="GROUP BY combined with WHERE and JOINs in a single SELECT",
                severity="info",
                suggestion="Split into a filtered_data CTE (WHERE+joins) and an aggregated_data CTE (GROUP BY)",
            ))
    return diagnostics


def check_distinct_without_justification(parsed: exp.Expression, sql_content: str) -> List[SQLDiagnostic]:
    """Rule: every DISTINCT must be accompanied by a justifying comment
    referencing the rule. Heuristic: look for keywords near the DISTINCT
    in the raw SQL."""
    diagnostics = []
    has_distinct = False
    for select in parsed.find_all(exp.Select):
        if select.args.get("distinct"):
            has_distinct = True
            break
    if not has_distinct:
        return diagnostics
    # Look for a comment justifying DISTINCT — any line containing
    # "DISTINCT" along with one of: "justified", "unavoidable",
    # "because", "due to", "necessary".
    justifying = ("justified", "unavoidable", "because", "due to", "necessary")
    found_comment = False
    for line in sql_content.splitlines():
        stripped = line.strip().lower()
        if not stripped.startswith("--") and "/*" not in stripped:
            continue
        if "distinct" in stripped and any(k in stripped for k in justifying):
            found_comment = True
            break
    if not found_comment:
        diagnostics.append(SQLDiagnostic(
            diagnostic_type="DISTINCT_WITHOUT_JUSTIFICATION",
            message="DISTINCT used without a justifying comment",
            severity="info",
            suggestion=(
                "Either replace DISTINCT with explicit deduplication "
                "(ROW_NUMBER OVER PARTITION BY ...) or add a comment "
                "explaining why DISTINCT is necessary"
            ),
        ))
    return diagnostics


def check_union_missing_source_tag(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: every UNION ALL branch must add a literal column tagging
    the originating source (`'A_SOURCE' AS source_ind`, `'CRE' AS source`,
    etc.). Detect by looking for at least one string-literal projection
    per branch."""
    diagnostics = []
    for union in parsed.find_all(exp.Union):
        for branch in (union.this, union.expression):
            if branch is None:
                continue
            branch_select = branch if isinstance(branch, exp.Select) else branch.find(exp.Select)
            if branch_select is None:
                continue
            has_literal_tag = False
            for proj in branch_select.expressions:
                inner = proj.this if isinstance(proj, exp.Alias) else proj
                if isinstance(inner, exp.Literal) and inner.is_string:
                    has_literal_tag = True
                    break
            if not has_literal_tag:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="UNION_MISSING_SOURCE_TAG",
                    message="UNION ALL branch lacks a source-identifying literal column",
                    severity="info",
                    suggestion="Add a literal column (e.g., 'CRE' AS source_ind) to identify the originating source",
                ))
    return diagnostics


def check_full_outer_with_coalesce(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: replace FULL OUTER JOIN + COALESCE with three-CTE pattern
    (LEFT JOIN/IS NULL × 2 + INNER JOIN, then UNION ALL)."""
    diagnostics = []
    for join in parsed.find_all(exp.Join):
        side = (join.args.get("side") or "").upper()
        kind = (join.args.get("kind") or "").upper()
        if side == "FULL" or kind == "FULL":
            # Find the outer Select; check whether its projection set
            # uses COALESCE.
            outer = join.parent
            while outer is not None and not isinstance(outer, exp.Select):
                outer = outer.parent
            if outer is None:
                continue
            has_coalesce = any(outer.find_all(exp.Coalesce))
            if has_coalesce:
                diagnostics.append(SQLDiagnostic(
                    diagnostic_type="FULL_OUTER_WITH_COALESCE",
                    message="FULL OUTER JOIN with COALESCE — replace with LEFT JOIN/IS NULL + INNER JOIN + UNION ALL pattern",
                    severity="warning",
                    suggestion="Restructure as three CTEs: unique_rows_from_a, unique_rows_from_b, matching_rows; UNION ALL",
                ))
                break  # one finding per query
    return diagnostics


def check_non_descriptive_cte_name(parsed: exp.Expression) -> List[SQLDiagnostic]:
    """Rule: CTE names should be descriptive (`filtered_*`, `*_filtered`,
    `transformed_*`, etc.). Flag CTEs named `t1`, `cte1`, `tmp`, `a`,
    `foo`, etc."""
    diagnostics = []
    bad_patterns = ("t1", "t2", "t3", "cte1", "cte2", "tmp", "temp", "foo", "bar", "a", "b", "c", "x", "y", "z")
    for cte in parsed.find_all(exp.CTE):
        name = (cte.alias_or_name or "").lower()
        if name in bad_patterns:
            diagnostics.append(SQLDiagnostic(
                diagnostic_type="NON_DESCRIPTIVE_CTE_NAME",
                message=f"CTE name '{cte.alias_or_name}' is not descriptive",
                severity="info",
                suggestion="Use descriptive names like <source>_filtered, transformed_data, aggregated_data, etc.",
            ))
    return diagnostics


def check_pk_dedup_missing(
    parsed: exp.Expression,
    sql_content: str,
) -> List[SQLDiagnostic]:
    """Rule: when @pk annotations are present, the query should also
    emit ROW_NUMBER + COUNT partitioned by the PK so downstream DQ
    checks can verify uniqueness. Detection only."""
    diagnostics = []
    # Look for @pk annotations in the raw SQL.
    if "@pk" not in sql_content:
        return diagnostics
    # If we have a ROW_NUMBER OVER (PARTITION BY ...) anywhere, assume
    # the dedup check is in place. Heuristic; conservative.
    has_partitioned_rownum = False
    for window in parsed.find_all(exp.Window):
        partition = window.args.get("partition_by")
        if partition:
            inner = window.this
            if isinstance(inner, exp.RowNumber):
                has_partitioned_rownum = True
                break
    if not has_partitioned_rownum:
        diagnostics.append(SQLDiagnostic(
            diagnostic_type="PK_DEDUP_CHECK_MISSING",
            message="@pk annotations present but no ROW_NUMBER PARTITION BY <pk> for dedup verification",
            severity="info",
            suggestion=(
                "Add `ROW_NUMBER() OVER (PARTITION BY <pk_cols> ORDER BY ...) AS _rn_per_pk` "
                "and `COUNT(*) OVER (PARTITION BY <pk_cols>) AS _cnt_per_pk` so downstream "
                "DQ checks can assert uniqueness"
            ),
        ))
    return diagnostics


def analyze_sql(
    sql_content: str,
    include_determinism: bool = True,
    config: dict = None,
) -> List[SQLDiagnostic]:
    """
    Run all checks on SQL content.

    Args:
        sql_content: SQL to analyze
        include_determinism: Whether to include determinism checks (default True)
        config: Optional customer-rule config dict (see top of file)

    Returns list of diagnostics.
    """
    try:
        parsed = sqlglot.parse_one(sql_content)
    except Exception as e:
        return [SQLDiagnostic(
            diagnostic_type="PARSE_ERROR",
            message=str(e),
            severity="error",
        )]

    config = config or {}
    diagnostics = []

    # Original 5 checks
    diagnostics.extend(check_select_star(parsed))
    diagnostics.extend(check_missing_alias(parsed))
    diagnostics.extend(check_order_by_number(parsed))
    diagnostics.extend(check_implicit_join(parsed))
    diagnostics.extend(check_where_one_equals_one(parsed))

    # Anti-pattern checks (expanding to 15)
    diagnostics.extend(check_distinct_star(parsed))
    diagnostics.extend(check_cartesian_join(parsed))
    diagnostics.extend(check_duplicate_column(parsed))
    diagnostics.extend(check_nested_subquery(parsed))
    diagnostics.extend(check_union_column_mismatch(parsed))
    diagnostics.extend(check_leading_wildcard(parsed))
    diagnostics.extend(check_function_in_where(parsed))
    diagnostics.extend(check_or_in_join(parsed))
    diagnostics.extend(check_hardcoded_date(parsed))
    diagnostics.extend(check_missing_group_by(parsed))

    # Customer rule-pack checks
    diagnostics.extend(check_legacy_schema(parsed, config))
    diagnostics.extend(check_legacy_date_variable(sql_content, config))
    diagnostics.extend(check_between_for_scd2(parsed))
    diagnostics.extend(check_obsolete_cte(parsed, config))
    diagnostics.extend(check_metadata_column_exposed(parsed, config))
    diagnostics.extend(check_unused_left_join(parsed))
    diagnostics.extend(check_inline_cast_in_join(parsed))
    diagnostics.extend(check_derivation_in_where(parsed))
    diagnostics.extend(check_inline_union_transform(parsed))
    diagnostics.extend(check_combined_source_filters(parsed))
    diagnostics.extend(check_groupby_not_isolated(parsed))
    diagnostics.extend(check_distinct_without_justification(parsed, sql_content))
    diagnostics.extend(check_union_missing_source_tag(parsed))
    diagnostics.extend(check_full_outer_with_coalesce(parsed))
    diagnostics.extend(check_non_descriptive_cte_name(parsed))
    diagnostics.extend(check_pk_dedup_missing(parsed, sql_content))

    # Determinism checks (critical for regression testing)
    if include_determinism:
        from _determinism import check_determinism
        for issue in check_determinism(sql_content):
            diagnostics.append(SQLDiagnostic(
                diagnostic_type=issue.issue_type,
                message=issue.message,
                severity=issue.severity,
                suggestion=issue.suggestion,
            ))

    return diagnostics


def get_all_check_types() -> List[str]:
    """Return list of all check types for documentation."""
    return [
        # Anti-pattern checks (15)
        "SELECT_STAR",
        "MISSING_ALIAS",
        "ORDER_BY_NUMBER",
        "IMPLICIT_JOIN",
        "WHERE_1_EQUALS_1",
        "DISTINCT_STAR",
        "CARTESIAN_JOIN",
        "DUPLICATE_COLUMN",
        "NESTED_SUBQUERY",
        "UNION_COLUMN_MISMATCH",
        "LEADING_WILDCARD",
        "FUNCTION_IN_WHERE",
        "OR_IN_JOIN",
        "HARDCODED_DATE",
        "MISSING_GROUP_BY",
        # Customer rule-pack checks (16)
        "LEGACY_SCHEMA",
        "LEGACY_DATE_VARIABLE",
        "BETWEEN_FOR_SCD2",
        "OBSOLETE_CTE",
        "METADATA_COLUMN_EXPOSED",
        "UNUSED_LEFT_JOIN",
        "INLINE_CAST_IN_JOIN",
        "LITERAL_IN_JOIN",
        "DERIVATION_IN_WHERE",
        "INLINE_UNION_TRANSFORM",
        "COMBINED_SOURCE_FILTERS",
        "GROUPBY_NOT_ISOLATED",
        "DISTINCT_WITHOUT_JUSTIFICATION",
        "UNION_MISSING_SOURCE_TAG",
        "FULL_OUTER_WITH_COALESCE",
        "NON_DESCRIPTIVE_CTE_NAME",
        "PK_DEDUP_CHECK_MISSING",
        # Determinism checks (5)
        "WINDOW_NO_ORDER",
        "WINDOW_NON_UNIQUE_ORDER",
        "LIMIT_NO_ORDER",
        "VOLATILE_FUNCTION",
        "FIRST_LAST_NO_ORDER",
    ]


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        # Demo with inline SQL showcasing multiple checks
        print("MDDE Lite - SQL Optimizer Demo (15 Checks)")
        print("=" * 60)

        # SQL that triggers multiple checks
        bad_sql = """
        SELECT DISTINCT *
        FROM products p
        JOIN categories ON categories.id = p.category_id
        JOIN inventory  -- Missing ON clause
        WHERE 1=1
          AND UPPER(product_name) = 'WIDGET'
          AND created_date > '2024-01-01'
          AND name LIKE '%test%'
        ORDER BY 1
        """

        print("Analyzing SQL:")
        print(bad_sql)
        print("\nDiagnostics Found:")

        diagnostics = analyze_sql(bad_sql)
        for diag in diagnostics:
            print(f"\n  [{diag.severity.upper()}] {diag.diagnostic_type}")
            print(f"    {diag.message}")
            if diag.suggestion:
                print(f"    Suggestion: {diag.suggestion}")

        print(f"\n" + "=" * 60)
        print(f"Total: {len(diagnostics)} issues found")
        print(f"\nAll available checks ({len(get_all_check_types())}):")
        for check in get_all_check_types():
            print(f"  - {check}")

    else:
        # Read a single file from argv and report.
        from pathlib import Path
        sql_path = Path(sys.argv[1])
        if sql_path.is_dir():
            print("Directory analysis is not available in the vendored "
                  "copy. Pass a single SQL file or use sql_process.py.")
            sys.exit(2)
        sql_content = sql_path.read_text()
        print(f"Analyzing {sql_path.name} ...")
        diagnostics = analyze_sql(sql_content)
        for d in diagnostics:
            print(f"  - {d}")
        print(f"\nTotal: {len(diagnostics)} issues found")
